ColonizeMars/src/Entity/Minerais.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MineraisRepository")
 */
class Minerais
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\Column(type="decimal", precision=2, scale=2)
     */
    private $Danger;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Zones", inversedBy="minerais")
     */
    private $Zones;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="minerais")
     */
    private $User;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="Minerai")
     */
    private $commentaires;

    public function __construct()
    {
        $this->Zones = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getDanger(): ?string
    {
        return $this->Danger;
    }

    public function setDanger(string $Danger): self
    {
        $this->Danger = $Danger;

        return $this;
    }

    /**
     * @return Collection|Zones[]
     */
    public function getZones(): Collection
    {
        return $this->Zones;
    }

    public function addZone(Zones $zone): self
    {
        if (!$this->Zones->contains($zone)) {
            $this->Zones[] = $zone;
        }

        return $this;
    }

    public function removeZone(Zones $zone): self
    {
        if ($this->Zones->contains($zone)) {
            $this->Zones->removeElement($zone);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setMinerai($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getMinerai() === $this) {
                $commentaire->setMinerai(null);
            }
        }

        return $this;
    }
}

ColonizeMars/src/Controller/DescriptifControllerPhpController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Minerais;

class DescriptifControllerPhpController extends AbstractController
{
    /**
     * @Route("/descriptif", name="descriptif_controller_php")
     */
    public function index()
    {
        return $this->render('descriptif_controller_php/index.html.twig', [
            'controller_name' => 'DescriptifControllerPhpController',
        ]);
    }
	/**
     * @Route("/klingon", name="descriptif_klingon")
     */
    public function klingon(){

		$repo = $this->getDoctrine()->getRepository(Minerais::class);

        $minerais = $repo->find(2);
//		var_dump($minerais);

		return $this->render('descriptif_controller_php/klingon.html.twig', [
			'title' => "klingon",
			'controller_name' => 'DescriptifControllerPhpController',
            'minerais' => $minerais,
		]);

	}
	/**
     * @Route("/chomdu", name="chomdu.html.twig")
     */
    public function chomdu(){

		$repo = $this->getDoctrine()->getRepository(Minerais::class);

        $minerais = $repo->find(3);
//		var_dump($minerais);

		return $this->render('descriptif_controller_php/chomdu.html.twig', [
			'title' => "chomdu",
			'controller_name' => 'DescriptifControllerPhpController',
            'minerais' => $minerais,
		]);

	}

	/**
     * @Route("/perl", name="perl.html.twig")
     */
    public function perl(){

		$repo = $this->getDoctrine()->getRepository(Minerais::class);

        $minerais = $repo->find(4);


		return $this->render('descriptif_controller_php/perl.html.twig', [
			'title' => "perl",
			'controller_name' => 'DescriptifControllerPhpController',
            'minerais' => $minerais,
		]);

	}
}

ColonizeMars/templates/descriptif_controller_php/chomdu.html.twig
{% extends 'base.html.twig' %}

{% block title %}chomdu{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
	<button><a href="/home">Retour</a></button>
    <h1>Le Chomdû !</h1>
</div>
<body>
	<h3>{{minerais.title}}</h3>
	<p>{{minerais.content}}</p>
	<p>{{minerais.date | date('d/m/Y')}}</p>
	<p>Niveau de dangerosité : {{minerais.danger}}</p>
</body>
<footer>
	<button>Contacter un scientifique</button>
</footer>
{% endblock %}

ColonizeMars/templates/descriptif_controller_php/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Descriptif{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
	<button><a href="/home">Retour à l'accueil</a></button>
    <h1>Description du minerai</h1>
    <p></p>

    <div>
    	<p></p>
    </div>

</div>
{% endblock %}

ColonizeMars/templates/descriptif_controller_php/klingon.html.twig
{% extends 'base.html.twig' %}

{% block title %}Klingon{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
	<button><a href="/home">Retour</a></button>
    <h1>Le Klingon !</h1>
</div>
<body>
	<h3>{{minerais.title}}</h3>
	<p>{{minerais.content}}</p>
	<p>{{minerais.date | date('d/m/Y')}}</p>
	<p>Niveau de dangerosité : {{minerais.danger}}</p>
</body>
<footer>
	<button>Contacter un scientifique</button>
</footer>
{% endblock %}

ColonizeMars/templates/descriptif_controller_php/perl.html.twig
{% extends 'base.html.twig' %}

{% block title %}Perl{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
	<button><a href="/home">Retour</a></button>
    <h1>Perl !</h1>
</div>
<body>
	<h3>{{minerais.title}}</h3>
	<p>{{minerais.content}}</p>
	<p>{{minerais.date | date('d/m/Y')}}</p>
	<p>Niveau de dangerosité : {{minerais.danger}}</p>
</body>
<footer>
	<button>Contacter un scientifique</button>
</footer>
{% endblock %}